<?php

namespace ActualiteBundle\Repository;

/**
 * ActualiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActualiteRepository extends \Doctrine\ORM\EntityRepository
{

    public function getAllActualites($recherche)
    {
        $qb = $this->createQueryBuilder('a');

        /**
         * recherche via le titre
         */
        if(!is_null($recherche)){
            $qb->andWhere('a.titre LIKE :recherche')
                ->setParameter('recherche', '%'.$recherche.'%');
        }

        $qb->orderBy('a.id', 'DESC');

        return $query = $qb->getQuery()->getResult();
    }

    public function getAllActualitesApi(){
        $qb = $this->createQueryBuilder('a');

        $qb->andWhere('a.isActive = :active')
           ->setParameter('active', true);

        $qb->orderBy('a.id', 'DESC');

        return $query = $qb->getQuery()->getArrayResult();
    }


}
