contact:
    resource: "@ContactBundle/Resources/config/routing.yml"
    prefix:   /

projet:
    resource: "@ProjetBundle/Resources/config/routing.yml"
    prefix:   /

competence:
    resource: "@CompetenceBundle/Resources/config/routing.yml"
    prefix:   /

actualite:
    resource: "@ActualiteBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

global:
    resource: "@GlobalBundle/Resources/config/routing.yml"
    prefix:   /