# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    custom.twig.extension.debug:
        class: Twig_Extension_Debug
        tags:
             - { name: 'twig.extension' }

    twig.extension.intl:
            class: Twig_Extensions_Extension_Intl
            tags:
                - { name: twig.extension }