<?php

namespace UserBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{

	public function getAllUser($username)
	{
		$qb = $this->createQueryBuilder('u');

		/**
		 * recherche via le username
		 */
		if(!is_null($username)){
			$qb->andWhere('u.username LIKE :username')
			   ->setParameter('username', '%'.$username.'%');
		}
		
		$qb->orderBy('u.id', 'DESC');

		return $query = $qb->getQuery()->getResult();
	}

}
