<?php

namespace CompetenceBundle\Repository;

/**
 * CompetenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompetenceRepository extends \Doctrine\ORM\EntityRepository
{

    public function getAllCompetences($recherche)
    {
        $qb = $this->createQueryBuilder('c');

        /**
         * recherche via le titre
         */
        if(!is_null($recherche)){
            $qb->andWhere('c.titre LIKE :recherche')
                ->setParameter('recherche', '%'.$recherche.'%');
        }

        $qb->orderBy('c.id', 'DESC');

        return $query = $qb->getQuery()->getResult();
    }

}
