<?php

namespace ProjetBundle\Repository;

/**
 * ProjetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetRepository extends \Doctrine\ORM\EntityRepository
{

    public function getAllProjets($recherche)
    {
        $qb = $this->createQueryBuilder('p');

        /**
         * recherche via le titre
         */
        if(!is_null($recherche)){
            $qb->andWhere('p.titre LIKE :recherche')
                ->setParameter('recherche', '%'.$recherche.'%');
        }

        $qb->orderBy('p.id', 'DESC');

        return $query = $qb->getQuery()->getResult();
    }

}
